[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_VERSION = "10.8.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*.json"]

